version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ~/db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # redundant
  proxy:
    image: tech-proxy
